export const dataS = {
  musicans: [
    {
      nameEN: "Franz Joseph Haydn",
      nameCN: "海顿",
      birthday: "1732年4月1日",
      nativeCountry: "奥地利",
      latitude: 48.4,
      longitude: 16.52,
      imgUrl: "https://z3.ax1x.com/2021/11/03/IAe76g.jpg",
    },
    {
      nameEN: "Carl Philipp Emanuel Bach",
      nameCN: "巴赫",
      birthday: "1714年3月8日",
      nativeCountry: "德国魏玛",
      latitude: 50.59,
      longitude: 11.19,
      imgUrl: "https://z3.ax1x.com/2021/11/03/IAejkq.jpg",
    },
    {
      nameEN: "Wolfgang Amadeus Mozart",
      nameCN: "莫扎特",
      birthday: "1756年1月27日",
      nativeCountry: "奥地利萨尔茨堡",
      latitude: 47.48,
      longitude: 13.02,
      imgUrl: "https://z3.ax1x.com/2021/11/03/IAeO7n.jpg",
    },
    {
      nameEN: "Ludwig van Beethoven",
      nameCN: "贝多芬",
      birthday: "1770年12月16日",
      nativeCountry: "神圣罗马帝国科隆选侯国波恩",
      latitude: 50.44,
      longitude: 7.6,
      imgUrl: "https://z3.ax1x.com/2021/11/03/IAeL0s.jpg",
    },
    {
      nameEN: "Franz Seraphicus Peter Schubert",
      nameCN: "舒伯特",
      birthday: "1797年1月31日",
      nativeCountry: "神圣罗马帝国维也纳",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Niccolò Paganini",
      nameCN: "帕格尼尼",
      birthday: "1782年10月27日",
      nativeCountry: "热那亚",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Maria Luigi Carlo Zenobio Salvatore Cherubini",
      nameCN: "凯鲁比尼",
      birthday: "1760年9月8日",
      nativeCountry: "佛罗伦萨",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Jakob Ludwig Felix Mendelssohn Bartholdy",
      nameCN: "门德尔松",
      birthday: "1809年2月3日",
      nativeCountry: "汉堡汉萨自由市",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Frédéric François Chopin",
      nameCN: "肖邦",
      birthday: "1810年3月1日",
      nativeCountry: "华沙公国热拉佐瓦沃拉",
      latitude: 52.15,
      longitude: 20.19,
      imgUrl: "https://z3.ax1x.com/2021/11/03/IAeHXQ.jpg",
    },
    {
      nameEN: "Robert Alexander Schumann",
      nameCN: "舒曼",
      birthday: "1810年6月8日",
      nativeCountry: "萨克森王国茨维考",
      latitude: 51.1,
      longitude: 13.21,
      imgUrl: "https://z3.ax1x.com/2021/11/03/IAevt0.jpg",
    },
    {
      nameEN: "Liszt Ferencz",
      nameCN: "李斯特",
      birthday: "1811年10月22日",
      nativeCountry: "奥地利帝国匈牙利",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Wilhelm Richard Wagner",
      nameCN: "瓦格纳",
      birthday: "1813年5月22日",
      nativeCountry: "萨克森王国莱比锡",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Johannes Brahms",
      nameCN: "勃拉姆斯",
      birthday: "1833年5月7日",
      nativeCountry: "普鲁士王国汉堡",
      latitude: 53.33,
      longitude: 10,
      imgUrl: "https://z3.ax1x.com/2021/11/03/IAeqmj.jpg",
    },
    {
      nameEN: "Johann Baptist Strauss",
      nameCN: "小约翰·施特劳斯",
      birthday: "1825年10月25日",
      nativeCountry: "奥地利帝国维也纳",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Georges Bizet",
      nameCN: "比才",
      birthday: "1838年10月25日",
      nativeCountry: "法兰西王国巴黎",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Charles Camille Saint-Saëns",
      nameCN: "圣桑",
      birthday: "1835年10月9日",
      nativeCountry: "法国巴黎",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Pyotr Ilyich Tchaikovsky",
      nameCN: "柴可夫斯基",
      birthday: "1840年5月7日",
      nativeCountry: "俄罗斯帝国维亚特卡省",
      latitude: 58.36,
      longitude: 49.39,
      imgUrl: "https://z3.ax1x.com/2021/11/03/IAexhV.jpg",
    },
    {
      nameEN: "Bedřich Smetana",
      nameCN: "斯美塔那",
      birthday: "1824年3月2日",
      nativeCountry: "奥地利帝国利托米什尔",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Antonín Leopold Dvořák",
      nameCN: "德沃夏克",
      birthday: "1841年9月8日",
      nativeCountry: "奥地利帝国波希米亚布拉格",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Jean Sibelius",
      nameCN: "西贝柳斯",
      birthday: "1865年12月8日",
      nativeCountry: "芬兰大公国海门林纳",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
    {
      nameEN: "Edvard Hagerup Grieg",
      nameCN: "格里格",
      birthday: "1843年6月15日",
      nativeCountry: "瑞典-挪威卑尔根",
      latitude: "",
      longitude: "",
      imgUrl: "",
    },
  ],
};
